steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "${_REPO_REGION}/$PROJECT_ID/${_REPO_NAME}/${_SERVICE_NAME}:latest",
        ".",
      ]
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "push",
        "${_REPO_REGION}/$PROJECT_ID/${_REPO_NAME}/${_SERVICE_NAME}:latest",
      ]
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      [
        "run",
        "deploy",
        "${_SERVICE_NAME}",
        "--image",
        "${_REPO_REGION}/$PROJECT_ID/${_REPO_NAME}/${_SERVICE_NAME}:latest",
        "--platform=managed",
        "--region=asia-southeast1",
        "--allow-unauthenticated",
      ]

logsBucket: "gs://buildlogging"
options:
  logging: GCS_ONLY
