gzip = true
stats = true
index-stats = true
index-as-update=true

elasticsearch-max-conns = 1
elasticsearch-max-seconds = 5
elasticsearch-max-bytes = 8000000

dropped-collections = true
dropped-databases = true

resume = true
resume-write-unsafe = true
resume-name = "default"
verbose = true

direct-read-namespaces = ["dev.vehicleviews"]

[[relate]]
namespace = "dev.vehicles"
with-namespace = "dev.vehicleviews"

[[mapping]]
namespace = "dev.vehicleviews"
index = "vehicles"


